title: Title of my Test Page
author: GitHubber
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: @goldenchaosgod
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

---
title: "Title McTitley"
date: 2019-02-18
---
